from pathlib import Path

from dotenv import load_dotenv


PROJECT_ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = PROJECT_ROOT / ".env"

load_dotenv(ENV_FILE)


def _getenv(key: str, default: str) -> str:
    from os import getenv

    return getenv(key, default)


def _getbool(key: str, default: bool) -> bool:
    fallback = "true" if default else "false"
    return _getenv(key, fallback).lower() in {"1", "true", "yes", "on"}


def _getfloat(key: str, default: float) -> float:
    return float(_getenv(key, str(default)))


OPENROUTER_API_KEY = _getenv("OPENROUTER_API_KEY", _getenv("GEMINI_API_KEY", ""))
OPENROUTER_BASE_URL = _getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
OPENROUTER_MODEL = _getenv("OPENROUTER_MODEL", "openai/gpt-4o-mini")
OPENROUTER_MODEL_GROUNDED_NOTES = _getenv(
    "OPENROUTER_MODEL_GROUNDED_NOTES",
    OPENROUTER_MODEL,
)
OPENROUTER_MODEL_TEACHING_OUTLINE = _getenv(
    "OPENROUTER_MODEL_TEACHING_OUTLINE",
    OPENROUTER_MODEL,
)
OPENROUTER_MODEL_STORYBOARD = _getenv(
    "OPENROUTER_MODEL_STORYBOARD",
    OPENROUTER_MODEL,
)
OPENROUTER_MODEL_BUILDER = _getenv(
    "OPENROUTER_MODEL_BUILDER",
    _getenv("OPENROUTER_MODEL_STRONG", OPENROUTER_MODEL),
)
OPENROUTER_EMBED_MODEL = _getenv("OPENROUTER_EMBED_MODEL", "openai/text-embedding-3-small")
OPENROUTER_EMBED_DIMENSIONS = int(_getenv("OPENROUTER_EMBED_DIMENSIONS", "1536"))
AGNO_DB_URL = _getenv("AGNO_DB_URL", "postgresql+psycopg://ai:ai@localhost:5532/ai")
AGNO_TABLE_NAME = _getenv("AGNO_TABLE_NAME", "video_pdf_knowledge")
PDF_DIR = _getenv("PDF_DIR", str(PROJECT_ROOT / "input" / "pdfs"))
PDF_CHUNK_SIZE = int(_getenv("PDF_CHUNK_SIZE", "3000"))
PDF_SPLIT_ON_PAGES = _getbool("PDF_SPLIT_ON_PAGES", True)
APPROX_CHARS_PER_TOKEN = int(_getenv("APPROX_CHARS_PER_TOKEN", "4"))

MAX_RETRIEVED_CHUNKS = int(_getenv("MAX_RETRIEVED_CHUNKS", "6"))
MAX_SOURCE_TOKENS = int(_getenv("MAX_SOURCE_TOKENS", "2200"))
MAX_SOURCE_CHARACTERS = int(_getenv("MAX_SOURCE_CHARACTERS", "9000"))
MAX_RETRIEVAL_CALLS_PER_WORKFLOW = int(_getenv("MAX_RETRIEVAL_CALLS_PER_WORKFLOW", "1"))
RETRIEVAL_SEARCH_CANDIDATES = int(_getenv("RETRIEVAL_SEARCH_CANDIDATES", "12"))
RETRIEVAL_DEDUPLICATION_THRESHOLD = _getfloat(
    "RETRIEVAL_DEDUPLICATION_THRESHOLD",
    0.9,
)

MAX_GROUNDED_NOTES_TOKENS = int(_getenv("MAX_GROUNDED_NOTES_TOKENS", "1200"))
MAX_GROUNDED_NOTES_CHARACTERS = int(_getenv("MAX_GROUNDED_NOTES_CHARACTERS", "5000"))
MAX_OUTLINE_INPUT_TOKENS = int(_getenv("MAX_OUTLINE_INPUT_TOKENS", "2600"))
MAX_OUTLINE_CHARACTERS = int(_getenv("MAX_OUTLINE_CHARACTERS", "10000"))
MAX_OUTLINE_SECTIONS = int(_getenv("MAX_OUTLINE_SECTIONS", "6"))
MAX_STORYBOARD_INPUT_TOKENS = int(_getenv("MAX_STORYBOARD_INPUT_TOKENS", "3800"))
MAX_STORYBOARD_CHARACTERS = int(_getenv("MAX_STORYBOARD_CHARACTERS", "15000"))
MAX_STORYBOARD_SCENES = int(_getenv("MAX_STORYBOARD_SCENES", "10"))
MAX_BUILDER_INPUT_TOKENS = int(_getenv("MAX_BUILDER_INPUT_TOKENS", "5200"))
MAX_BUILDER_CHARACTERS = int(_getenv("MAX_BUILDER_CHARACTERS", "20000"))

STAGE_OUTPUT_MAX_TOKENS_GROUNDED_NOTES = int(
    _getenv("STAGE_OUTPUT_MAX_TOKENS_GROUNDED_NOTES", "1200")
)
STAGE_OUTPUT_MAX_TOKENS_OUTLINE = int(_getenv("STAGE_OUTPUT_MAX_TOKENS_OUTLINE", "1800"))
STAGE_OUTPUT_MAX_TOKENS_STORYBOARD = int(
    _getenv("STAGE_OUTPUT_MAX_TOKENS_STORYBOARD", "3200")
)
STAGE_OUTPUT_MAX_TOKENS_BUILDER = int(_getenv("STAGE_OUTPUT_MAX_TOKENS_BUILDER", "7000"))

MAX_SCENE_NARRATION_WORDS = int(_getenv("MAX_SCENE_NARRATION_WORDS", "70"))
MAX_ON_SCREEN_WORDS_PER_SCENE = int(_getenv("MAX_ON_SCREEN_WORDS_PER_SCENE", "18"))
MAX_TOTAL_LESSON_DURATION_SEC = int(_getenv("MAX_TOTAL_LESSON_DURATION_SEC", "900"))
